# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "fancy"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "fancy"

	[light_sources.settings]

		[light_sources.settings.block_entities]

			[light_sources.settings.block_entities.minecraft]
				bed = true
				calibrated_sculk_sensor = true
				furnace = true
				dropper = true
				daylight_detector = true
				jukebox = true
				sign = true
				brewing_stand = true
				sculk_sensor = true
				hanging_sign = true
				brushable_block = true
				conduit = true
				beehive = true
				dispenser = true
				smoker = true
				lectern = true
				skull = true
				campfire = true
				barrel = true
				chest = true
				piston = true
				sculk_shrieker = true
				end_portal = true
				shulker_box = true
				enchanting_table = true
				banner = true
				structure_block = true
				sculk_catalyst = true
				ender_chest = true
				bell = true
				end_gateway = true
				comparator = true
				beacon = true
				command_block = true
				jigsaw = true
				hopper = true
				mob_spawner = true
				chiseled_bookshelf = true
				trapped_chest = true
				decorated_pot = true
				blast_furnace = true

			[light_sources.settings.block_entities.farmersdelight]
				basket = true
				canvas_sign = true
				stove = true
				cutting_board = true
				skillet = true
				cabinet = true
				cooking_pot = true

			[light_sources.settings.block_entities.bitsandchisels]
				bits_block_entity = true

			[light_sources.settings.block_entities.easyanvils]
				anvil = true

			[light_sources.settings.block_entities.rechiseledcreate]
				mechanical_chisel = true

			[light_sources.settings.block_entities.deeperdarker]
				sign = true
				hanging_sign = true

			[light_sources.settings.block_entities.easymagic]
				enchanting_table = true

			[light_sources.settings.block_entities.railways]
				invisible_mono_bogey = true
				track_coupler = true
				conductor_whistle = true
				bogey = true
				track_switch_brass = true
				invisible_bogey = true
				casing_collision = true
				semaphore = true
				mono_bogey = true
				track_switch_andesite = true
				diesel_smokestack = true

			[light_sources.settings.block_entities.snowrealmagic]
				texture_tile = true
				snow = true

			[light_sources.settings.block_entities.seasonsextras]
				greenhouse_glass = true
				air_conditioning = true
				season_calendar = true
				season_detector = true

			[light_sources.settings.block_entities.extended_drawers]
				compacting_drawer = true
				drawer = true
				shadow_drawer = true

			[light_sources.settings.block_entities.visualworkbench]
				crafting_table = true

			[light_sources.settings.block_entities.display_case]
				display_case = true

			[light_sources.settings.block_entities.doggomodoverhauled]
				dog_bowl_entity = true

			[light_sources.settings.block_entities.winterly]
				gift_box = true

			[light_sources.settings.block_entities.yigd]
				grave_block_entity = true

			[light_sources.settings.block_entities.create]
				clockwork_bearing = true
				funnel = true
				hand_crank = true
				simple_kinetic = true
				clipboard = true
				rope_pulley = true
				harvester = true
				display_link = true
				lectern_controller = true
				encased_shaft = true
				item_drain = true
				belt = true
				backtank = true
				chassis = true
				gantry_pinion = true
				steam_engine = true
				clutch = true
				toolbox = true
				fake_track = true
				cuckoo_clock = true
				track_observer = true
				peculiar_bell = true
				motor = true
				pulse_extender = true
				elevator_contact = true
				sequenced_gearshift = true
				crushing_wheel = true
				mechanical_roller = true
				spout = true
				gearbox = true
				powered_shaft = true
				stockpile_switch = true
				andesite_tunnel = true
				stressometer = true
				smart_chute = true
				sticker = true
				encased_large_cogwheel = true
				nixie_tube = true
				water_wheel = true
				mechanical_piston = true
				mechanical_press = true
				bogey = true
				track_signal = true
				smart_fluid_pipe = true
				portable_storage_interface = true
				crushing_wheel_controller = true
				pulse_repeater = true
				mechanical_bearing = true
				schematicannon = true
				depot = true
				chute = true
				sliding_door = true
				fluid_pipe = true
				encased_cogwheel = true
				mechanical_crafter = true
				copycat = true
				cursed_bell = true
				hose_pulley = true
				rotation_speed_controller = true
				creative_crate = true
				basin = true
				encased_fluid_pipe = true
				fluid_valve = true
				brass_tunnel = true
				fluid_tank = true
				schematic_table = true
				portable_fluid_interface = true
				analog_lever = true
				adjustable_chain_gearshift = true
				windmill_bearing = true
				speedometer = true
				creative_fluid_tank = true
				millstone = true
				flap_display = true
				turntable = true
				gantry_shaft = true
				mechanical_arm = true
				item_vault = true
				blaze_heater = true
				flywheel = true
				weighted_ejector = true
				content_observer = true
				deployer = true
				track = true
				track_station = true
				elevator_pulley = true
				saw = true
				drill = true
				valve_handle = true
				mechanical_pump = true
				mechanical_mixer = true
				nozzle = true
				cart_assembler = true
				steam_whistle = true
				large_water_wheel = true
				encased_fan = true
				glass_fluid_pipe = true
				gearshift = true
				contraption_controls = true
				redstone_link = true
				placard = true

			[light_sources.settings.block_entities.supplementaries]
				pedestal = true
				clock_block = true
				wall_lantern = true
				blackboard = true
				flag = true
				sack = true
				speaker_block = true
				key_lockable_tile = true
				bubble_block = true
				bellows = true
				notice_board = true
				skull_pile = true
				ceiling_banner = true
				jar_boat = true
				cage = true
				skull_candle = true
				bamboo_spikes = true
				trapped_present = true
				hourglass = true
				wind_vane = true
				doormat = true
				jar = true
				spring_launcher_arm = true
				item_shelf = true
				enderman_head = true
				turn_table = true
				faucet = true
				structure_temp = true
				block_generator = true
				book_pile = true
				rope_knot = true
				hanging_flower_pot = true
				statue = true
				goblet = true
				urn = true
				flower_box = true
				pulley_block = true
				globe = true
				timber_frame = true
				safe = true
				present = true
				sign_post = true

			[light_sources.settings.block_entities.sliceanddice]
				slicer = true
				sprinkler = true

			[light_sources.settings.block_entities.expandeddelight]
				juicer = true

			[light_sources.settings.block_entities.cookingforblockheads]
				fridge = true
				oven = true
				cooking_table = true
				sink = true
				cow_jar = true
				counter = true
				tool_rack = true
				fruit_basket = true
				spice_rack = true
				corner = true
				cutting_board = true
				toaster = true
				milk_jar = true
				cabinet = true

			[light_sources.settings.block_entities.comforts]
				sleeping_bag = true
				hammock = true

			[light_sources.settings.block_entities.travelersbackpack]
				travelers_backpack = true

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				axolotl = true
				egg = true
				zoglin = true
				spawner_minecart = true
				allay = true
				llama = true
				mule = true
				bat = true
				husk = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				giant = true
				drowned = true
				item = true
				goat = true
				horse = true
				vindicator = true
				minecart = true
				spectral_arrow = true
				llama_spit = true
				mooshroom = true
				glow_item_frame = false
				snowball = true
				tnt = true
				parrot = true
				creeper = true
				lightning_bolt = true
				tadpole = true
				ravager = true
				evoker_fangs = true
				chest_minecart = true
				tropical_fish = true
				slime = true
				pillager = true
				area_effect_cloud = true
				piglin = true
				blaze = true
				endermite = true
				end_crystal = true
				zombie = true
				ender_pearl = true
				item_display = true
				guardian = true
				fireball = true
				illusioner = true
				eye_of_ender = true
				wither_skull = true
				wolf = true
				zombie_villager = true
				tnt_minecart = true
				block_display = true
				elder_guardian = true
				chest_boat = true
				boat = true
				small_fireball = true
				strider = true
				cave_spider = true
				witch = true
				cod = true
				snow_golem = true
				spider = true
				command_block_minecart = true
				panda = true
				bee = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				frog = true
				hoglin = true
				armor_stand = true
				experience_orb = true
				dolphin = true
				stray = true
				shulker = true
				turtle = true
				salmon = true
				wither_skeleton = true
				vex = true
				wandering_trader = true
				piglin_brute = true
				ocelot = true
				furnace_minecart = true
				item_frame = true
				phantom = true
				ender_dragon = true
				leash_knot = true
				evoker = true
				marker = true
				glow_squid = true
				warden = true
				squid = true
				shulker_bullet = true
				enderman = true
				dragon_fireball = true
				chicken = true
				sniffer = true
				trader_llama = true
				donkey = true
				fox = true
				iron_golem = true
				zombified_piglin = true
				cat = true
				ghast = true
				sheep = true
				player = true
				pufferfish = true
				potion = true
				trident = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				text_display = true
				polar_bear = true
				hopper_minecart = true
				falling_block = true
				painting = true
				interaction = true
				wither = true

			[light_sources.settings.entities.farmersdelight]
				rotten_tomato = true

			[light_sources.settings.entities.immersive_paintings]
				glow_graffiti = true
				painting = true
				graffiti = true
				glow_painting = true

			[light_sources.settings.entities.xercapaint]
				canvas = true
				easel = true

			[light_sources.settings.entities.guardvillagers]
				guard = true

			[light_sources.settings.entities.connectiblechains]
				chain_knot = true
				chain_collision = true

			[light_sources.settings.entities.deeperdarker]
				shattered = true
				stalker = true
				shriek_worm = true
				sculk_centipede = true
				sculk_leech = true
				chest_boat = true
				boat = true
				sculk_snapper = true

			[light_sources.settings.entities.railways]
				conductor = true
				benchcart = true
				jukeboxcart = true

			[light_sources.settings.entities.illagerinvasion]
				skull_bolt = true
				sorcerer = true
				alchemist = true
				surrendered = true
				necromancer = true
				basher = true
				firecaller = true
				invoker = true
				marauder = true
				invoker_fangs = true
				flying_magma = true
				hatchet = true
				provoker = true
				archivist = true
				inquisitor = true

			[light_sources.settings.entities.snowrealmagic]
				snow = true

			[light_sources.settings.entities.immersive_portals]
				nether_portal_new = true
				mirror = true
				border_portal = true
				global_tracked_portal = true
				end_portal = true
				end_floor_portal = true
				loading_indicator = true
				general_breakable_portal = true
				portal = true
				breakable_mirror = true

			[light_sources.settings.entities.doggomodoverhauled]
				tennis_ball_red_entity = true
				doggo = true
				tennis_ball_lime_entity = true
				tennis_ball_yellow_entity = true
				tennis_ball_light_blue_entity = true

			[light_sources.settings.entities.dummmmmmy]
				target_dummy = true

			[light_sources.settings.entities.create]
				carriage_contraption = true
				seat = true
				stationary_contraption = true
				contraption = true
				gantry_contraption = true
				super_glue = true
				crafting_blueprint = true
				potato_projectile = true

			[light_sources.settings.entities.supplementaries]
				dispenser_minecart = true
				slingshot_projectile = true
				falling_ash = true
				falling_lantern = true
				falling_urn = true
				brick_projectile = true
				pearl_marker = true
				falling_sack = true
				red_merchant = true
				bomb = true
				rope_arrow = true
				hat_stand = true

			[light_sources.settings.entities.friendsandfoes]
				glare = true
				copper_golem = true
				player_illusion = true
				ice_chunk = true
				moobloom = true
				tuff_golem = true
				mauler = true
				iceologer = true
				wildfire = true
				rascal = true

			[light_sources.settings.entities.wildlife]
				snail = true
				spicebush_butterfly = true
				monkey = true
				koi = true
				bluegill = true
				possum = true
				ladybug = true
				morpho_butterfly = true
				catfish = true
				glow_jellyfish = true
				boar = true
				anteater = true
				cottonbird = true
				anglerfish = true
				hermitcrab = true
				armadillo = true
				glasswing_butterfly = true
				seaurchin = true
				tiger_butterfly = true
				phoebe = true
				beaver = true
				seahorse = true
				june_beetle = true
				python = true
				chameleon = true
				hamster = true
				stickbug = true
				milk_snake = true
				grass_snake = true
				bluebird = true
				gecko = true
				hedgehog = true
				deer = true
				rhino_beetle = true
				alligator = true
				bettafish = true
				shrimp = true
				jellyfish = true
				hammerhead_shark = true
				stingray = true
				sanddollar = true
				dragonfly = true
				robin = true
				goldfish = true
				king_snake = true
				iguana = true
				capybara = true
				staghorn_beetle = true
				rainbow_trout = true
				sparrow = true
				porcupine = true
				lark = true
				starfish = true
				mantaray = true
				swallow = true
				oriole = true
				flycatcher = true
				ant = true
				monarch_butterfly = true
				prawn = true
				towhee = true
				sunflowerbeetle = true
				badger = true
				goldfinch = true
				chickadee = true
				wren = true
				horseshoecrab = true
				cricket = true
				clam = true
				ferret = true
				white_eye = true
				spider = true
				meadowlark = true
				crab = true

			[light_sources.settings.entities.hybrid-aquatic]
				crab = true
				fiddler_crab = true
				hermit_crab = true
				barrel_jellyfish = true
				sea_nettle = true
				compass_jellyfish = true
				ratfish = true
				needlefish = true
				yellowfin_tuna = true
				rockfish = true
				opah = true
				vampire_squid = true
				anglerfish = true
				glowing_sucker_octopus = true
				dragonfish = true
				sea_cucumber = true
				barreleye = true
				mahimahi = true
				giant_clam = true
				blue_jellyfish = true
				sea_urchin = true
				starfish = true
				blue_spotted_stingray = true
				toadfish = true
				moon_jellyfish = true
				stonefish = true
				mauve_stinger = true
				triggerfish = true
				cowfish = true
				atolla_jellyfish = true
				nomura_jellyfish = true
				great_white_shark = true
				firefly_squid = true
				flashlight_fish = true
				lions_mane_jellyfish = true
				cuttlefish = true
				moray_eel = true
				unicorn_fish = true
				blue_tang = true
				clownfish = true
				seahorse = true
				lionfish = true
				zebra_danio = true
				discus = true
				betta = true
				piranha = true
				oscar = true

			[light_sources.settings.entities.snuffles]
				snuffle = true

			[light_sources.settings.entities.niftycarts]
				supply_cart = true
				plow = true
				animal_cart = true

			[light_sources.settings.entities.items_displayed]
				item_display = true

			[light_sources.settings.entities.sit]
				entity_sit = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.terraform]
				boat = true

			[light_sources.settings.entities.handcrafted]
				seat = true
				fancy_painting = true

			[light_sources.settings.entities.doapi]
				chair = true

			[light_sources.settings.entities.vinery]
				wandering_winemaker = true
				mule = true

			[light_sources.settings.entities.psychedelicraft]
				molotov_cocktail = true

