enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 384
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = false
powderSnowCulling = false
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
customportalapi = true
consistency_plus = true
farmersdelight = true
seasonsextras = true
supplementaries = true
enchanted-vertical-slabs = true
cookingforblockheads = true
chipped = true
deeperdarker = true
winterly = true
endrem = true
create = true
immersive_portals = true
connectedglass = true
extended_drawers = true
friendsandfoes = true
minecraft = true
comforts = true
bitsandchisels = true
yigd = true
sliceanddice = true
travelersbackpack = true
moreslabs = true
railways = true
doggomodoverhauled = true
beautify = true
milk = true
display_case = true
snowrealmagic = true
rechiseledcreate = true
bushierflowers = true
abverticaledition = true
illagerinvasion = true
expandeddelight = true
rechiseled = true
gravestones = true
